AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  EmailSubscriber:
    Description:  "" 
    Type: String
    Default: "brian.pfeil@gmail.com"

Resources:

  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: src/handlers/hello-from-lambda.helloFromLambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Role: !GetAtt  lambdaRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref s3Bucket
          MY_SNS_TOPIC_ARN: !Ref mySnsEmailTopic
          MY_SNS_TOPIC_NAME: !GetAtt mySnsEmailTopic.TopicName
          MY_QUEUE_URL: !Ref myQueue
          MY_QUEUE_ARN: !GetAtt myQueue.Arn
          MY_QUEUE_NAME: !GetAtt  myQueue.QueueName

  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled 
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'


  lambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource: !Sub "arn:aws:s3:::${s3Bucket}"
              - Effect: "Allow"
                Action: "s3:*"
                Resource: !Sub "arn:aws:s3:::${s3Bucket}/*"

  myQueue:
    Type: AWS::SQS::Queue

  mySnsEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref EmailSubscriber
          Protocol: email
